### ISSUE TITLE
out of scope

### ISSUE THREAD

**Issue by jonschlinkert** [tunnckoCore/code-comments-regex#2]
This project doesn't belong here as-is. My understand of this org was that it would have regular expressions, not applications. e.g. 

This is what I would expect from a regex repo:

``` js
module.exports = /foo/;
```

or 

``` js
module.exports = function(){
  return  /foo/;
};
```

Not applications for using said regex.

**Comment by kevva** [comment]
+1

**Comment by tunnckoCore** [comment]
@johnotander @kevva 
Your expectations are right. My purpose with this repo was to just prettier look of long issue comments (specially)  for this regex app. And move discussion from `meta` repo to this one. Because we are here to share knowledge and discuss thoughts about regexes in one place, not in separate acc repos. That was the purpose, but okey will move it to my account, if this is so bad this.

**Comment by tunnckoCore** [comment]
Ready.
